# Native DAIMOS KCC build. Generated files are kept in BUILD/.
# Keep prerequisites grouped in readable lines (about 96 characters);
# use portable backslash continuations within the 256-character logical-line
# limit of native MAKE.  Do not regenerate at boot.
NATIVE_BUILD_DIR = BUILD
KCC_NATIVE_FLAGS = -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI
# Archive and DLINK recipes use ordered prerequisites with $^.
# DLINK dependencies put startup objects before phase archives.
NATIVE_DARC = /OPTION/BASE/EXEC/DARC
NATIVE_DLINK = /OPTION/BASE/EXEC/DLINK
NATIVE_RM = /SYSTEM/EXEC/RM
.PHONY: NATIVE INSTALL CLEAN
NATIVE: BUILD BUILD/KCPP.DXR BUILD/KPARSE.DXR BUILD/KGEN.DXR BUILD/KOPT.DXR BUILD/KCC.DXR
BUILD:
	@/SYSTEM/EXEC/INSTALL -D -M 0777 BUILD
BUILD/KCPP1.DARC: BUILD/CC-CPP.DOBJ BUILD/CCASMB.DOBJ BUILD/CCDATA-CPP.DOBJ BUILD/CCERR-CPP.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KCPP2.DARC: BUILD/CCOUT-CPP.DOBJ BUILD/CCPP.DOBJ BUILD/CCPPOUT.DOBJ BUILD/CCSYM-CPP.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KCPP3.DARC: BUILD/CCSRC.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KCPP.DXR: BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ BUILD/KCPP1.DARC \
    BUILD/KCPP2.DARC BUILD/KCPP3.DARC BOOT/LIBC.DARC
	@$(NATIVE_DLINK) --DAIMOS-UUO-RELAX -B 020 -O $@ $^
BUILD/KPARSE1.DARC: BUILD/CC-PARSE.DOBJ BUILD/CCASMB.DOBJ BUILD/CCDATA-PARSE.DOBJ BUILD/CCBIND-PARSE.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KPARSE2.DARC: BUILD/CCDBUG.DOBJ BUILD/CCDECL.DOBJ BUILD/CCERR-PARSE.DOBJ BUILD/CCEVAL.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KPARSE3.DARC: BUILD/CCLEX.DOBJ BUILD/CCNODE.DOBJ BUILD/CCPPIN.DOBJ BUILD/CCSTMT.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KPARSE4.DARC: BUILD/CCSYM.DOBJ BUILD/CCTYPE.DOBJ BUILD/CCOUTUTIL.DOBJ BUILD/CCKIRWRITE.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KPARSE5.DARC: BUILD/CCVLA.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KPARSE-RT.DARC: BUILD/DAIMOS-CHAIN.DOBJ BUILD/DAIMOS-PATH.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KPARSE.DXR: BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ BUILD/KPARSE1.DARC \
    BUILD/KPARSE2.DARC BUILD/KPARSE3.DARC BUILD/KPARSE4.DARC BUILD/KPARSE5.DARC BUILD/KPARSE-RT.DARC \
    BOOT/LIBC.DARC
	@$(NATIVE_DLINK) --DAIMOS-UUO-RELAX -B 020 -O $@ $^
BUILD/KGEN1.DARC: BUILD/CCKGEN-GEN.DOBJ BUILD/CCCREG.DOBJ BUILD/CCCSE.DOBJ BUILD/CCCODE-GEN.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN2.DARC: BUILD/CCDATA-GEN.DOBJ BUILD/CCDBUG.DOBJ BUILD/CCERR-GEN.DOBJ BUILD/CCEVALGEN.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN3.DARC: BUILD/CCGEN-GEN.DOBJ BUILD/CCGEN1-GEN.DOBJ BUILD/CCGEN2.DOBJ BUILD/CCGSWI.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN4.DARC: BUILD/CCJSKP.DOBJ BUILD/CCNODE-GEN.DOBJ BUILD/CCREG.DOBJ BUILD/CCSYM-GEN.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN5.DARC: BUILD/CCTYPE-GEN.DOBJ BUILD/CCOPT.DOBJ BUILD/CCOUTUTIL.DOBJ BUILD/CCKPOUT-GEN.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN6.DARC: BUILD/CCKPWRITE-GEN.DOBJ BUILD/CCKIRREAD.DOBJ BUILD/CCVLA.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN-RT.DARC: BUILD/DAIMOS-CHAIN.DOBJ BUILD/DAIMOS-PATH.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN.DXR: BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ BUILD/KGEN1.DARC \
    BUILD/KGEN2.DARC BUILD/KGEN3.DARC BUILD/KGEN4.DARC BUILD/KGEN5.DARC BUILD/KGEN6.DARC BUILD/KGEN-RT.DARC \
    BOOT/LIBC.DARC
	@$(NATIVE_DLINK) --DAIMOS-UUO-RELAX -B 020 -O $@ $^
BUILD/KOPT1.DARC: BUILD/CCKOPT-OPT.DOBJ BUILD/CCKPREAD-OPT.DOBJ BUILD/CCOUT-OPT.DOBJ BUILD/CCOUTUTIL.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KOPT2.DARC: BUILD/CCDATA-OPT.DOBJ BUILD/CCERR-OPT.DOBJ BUILD/CCASMB.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KOPT-RT.DARC: BUILD/DAIMOS-PATH.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KOPT.DXR: BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ BUILD/KOPT1.DARC \
    BUILD/KOPT2.DARC BUILD/KOPT-RT.DARC BOOT/LIBC.DARC
	@$(NATIVE_DLINK) --DAIMOS-UUO-RELAX -B 020 -O $@ $^
BUILD/CC-CPP.S: B CC.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSITE.H CCSYM.H \
    CCTOKS.H KCCHST.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_CPP=1 CC.C
BUILD/CC-CPP.DOBJ: BUILD/CC-CPP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CC-PARSE.S: B CC.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSITE.H CCSYM.H \
    CCTOKS.H KCCHST.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_PARSE=1 CC.C
BUILD/CC-PARSE.DOBJ: BUILD/CC-PARSE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCASMB.S: B CCASMB.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSITE.H CCSYM.H \
    CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCASMB.C
BUILD/CCASMB.DOBJ: BUILD/CCASMB.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCBIND-PARSE.S: B CCBIND.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_PARSE=1 CCBIND.C
BUILD/CCBIND-PARSE.DOBJ: BUILD/CCBIND-PARSE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCCODE-GEN.S: B CCCODE.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H \
    CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCCODE.C
BUILD/CCCODE-GEN.DOBJ: BUILD/CCCODE-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCCREG.S: B CCCREG.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCCREG.C
BUILD/CCCREG.DOBJ: BUILD/CCCREG.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCCSE.S: B CCCSE.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCCSE.C
BUILD/CCCSE.DOBJ: BUILD/CCCSE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCDATA-CPP.S: B CCDATA.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCLEX.H \
    CCNODE.H CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_CPP=1 CCDATA.C
BUILD/CCDATA-CPP.DOBJ: BUILD/CCDATA-CPP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCDATA-GEN.S: B CCDATA.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCLEX.H \
    CCNODE.H CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCDATA.C
BUILD/CCDATA-GEN.DOBJ: BUILD/CCDATA-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCDATA-OPT.S: B CCDATA.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCLEX.H \
    CCNODE.H CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_OPT=1 CCDATA.C
BUILD/CCDATA-OPT.DOBJ: BUILD/CCDATA-OPT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCDATA-PARSE.S: B CCDATA.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCLEX.H \
    CCNODE.H CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_PARSE=1 CCDATA.C
BUILD/CCDATA-PARSE.DOBJ: BUILD/CCDATA-PARSE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCDBUG.S: B CCDBUG.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCDBUG.C
BUILD/CCDBUG.DOBJ: BUILD/CCDBUG.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCDECL.S: B CCDECL.C C-ENV.H CC.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H \
    CCVLA.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCDECL.C
BUILD/CCDECL.DOBJ: BUILD/CCDECL.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCERR-CPP.S: B CCERR.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_CPP=1 CCERR.C
BUILD/CCERR-CPP.DOBJ: BUILD/CCERR-CPP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCERR-GEN.S: B CCERR.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCERR.C
BUILD/CCERR-GEN.DOBJ: BUILD/CCERR-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCERR-OPT.S: B CCERR.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_OPT=1 CCERR.C
BUILD/CCERR-OPT.DOBJ: BUILD/CCERR-OPT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCERR-PARSE.S: B CCERR.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H \
    CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_PARSE=1 CCERR.C
BUILD/CCERR-PARSE.DOBJ: BUILD/CCERR-PARSE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCEVAL.S: B CCEVAL.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCEVAL.C
BUILD/CCEVAL.DOBJ: BUILD/CCEVAL.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCEVALGEN.S: B CCEVALGEN.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCEVALGEN.C
BUILD/CCEVALGEN.DOBJ: BUILD/CCEVALGEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCGEN-GEN.S: B CCGEN.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCNODE.H \
    CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCGEN.C
BUILD/CCGEN-GEN.DOBJ: BUILD/CCGEN-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCGEN1-GEN.S: B CCGEN1.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H \
    CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCGEN1.C
BUILD/CCGEN1-GEN.DOBJ: BUILD/CCGEN1-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCGEN2.S: B CCGEN2.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCGEN2.C
BUILD/CCGEN2.DOBJ: BUILD/CCGEN2.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCGSWI.S: B CCGSWI.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCGSWI.C
BUILD/CCGSWI.DOBJ: BUILD/CCGSWI.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCJSKP.S: B CCJSKP.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCJSKP.C
BUILD/CCJSKP.DOBJ: BUILD/CCJSKP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCKGEN-GEN.S: B CCKGEN.C C-ENV.H CC.H CCERR.H CCKIR.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCKGEN.C
BUILD/CCKGEN-GEN.DOBJ: BUILD/CCKGEN-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCKIRREAD.S: B CCKIRREAD.C C-ENV.H CC.H CCERR.H CCKIR.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H CCVLA.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCKIRREAD.C
BUILD/CCKIRREAD.DOBJ: BUILD/CCKIRREAD.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCKIRWRITE.S: B CCKIRWRITE.C C-ENV.H CC.H CCERR.H CCKIR.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H CCVLA.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCKIRWRITE.C
BUILD/CCKIRWRITE.DOBJ: BUILD/CCKIRWRITE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCKOPT-OPT.S: B CCKOPT.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCKPCODE.H CCNODE.H \
    CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_OPT=1 CCKOPT.C
BUILD/CCKOPT-OPT.DOBJ: BUILD/CCKOPT-OPT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCKPOUT-GEN.S: B CCKPOUT.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCKPCODE.H CCNODE.H \
    CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCKPOUT.C
BUILD/CCKPOUT-GEN.DOBJ: BUILD/CCKPOUT-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCKPREAD-OPT.S: B CCKPREAD.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCKPCODE.H CCNODE.H \
    CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_OPT=1 CCKPREAD.C
BUILD/CCKPREAD-OPT.DOBJ: BUILD/CCKPREAD-OPT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCKPWRITE-GEN.S: B CCKPWRITE.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCKPCODE.H \
    CCNODE.H CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCKPWRITE.C
BUILD/CCKPWRITE-GEN.DOBJ: BUILD/CCKPWRITE-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCLEX.S: B CCLEX.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCLEX.C
BUILD/CCLEX.DOBJ: BUILD/CCLEX.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCNODE.S: B CCNODE.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCNODE.C
BUILD/CCNODE.DOBJ: BUILD/CCNODE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCNODE-GEN.S: B CCNODE.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCNODE.C
BUILD/CCNODE-GEN.DOBJ: BUILD/CCNODE-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCOPT.S: B CCOPT.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCOPT.C
BUILD/CCOPT.DOBJ: BUILD/CCOPT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCOUT-CPP.S: B CCOUT.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCNODE.H \
    CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_CPP=1 CCOUT.C
BUILD/CCOUT-CPP.DOBJ: BUILD/CCOUT-CPP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCOUT-OPT.S: B CCOUT.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCNODE.H \
    CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_OPT=1 CCOUT.C
BUILD/CCOUT-OPT.DOBJ: BUILD/CCOUT-OPT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCOUTUTIL.S: B CCOUTUTIL.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H \
    CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCOUTUTIL.C
BUILD/CCOUTUTIL.DOBJ: BUILD/CCOUTUTIL.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCPP.S: B CCPP.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSRC.H \
    CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCPP.C
BUILD/CCPP.DOBJ: BUILD/CCPP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCPPIN.S: B CCPPIN.C C-ENV.H CC.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCPHASE.H CCSYM.H \
    CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCPPIN.C
BUILD/CCPPIN.DOBJ: BUILD/CCPPIN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCPPOUT.S: B CCPPOUT.C C-ENV.H CC.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCPHASE.H \
    CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCPPOUT.C
BUILD/CCPPOUT.DOBJ: BUILD/CCPPOUT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCREG.S: B CCREG.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCREG.C
BUILD/CCREG.DOBJ: BUILD/CCREG.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCSRC.S: B CCSRC.C CCSRC.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCSRC.C
BUILD/CCSRC.DOBJ: BUILD/CCSRC.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCSTMT.S: B CCSTMT.C C-ENV.H CC.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCSTMT.C
BUILD/CCSTMT.DOBJ: BUILD/CCSTMT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCSYM.S: B CCSYM.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCSYM.C
BUILD/CCSYM.DOBJ: BUILD/CCSYM.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCSYM-CPP.S: B CCSYM.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_CPP=1 CCSYM.C
BUILD/CCSYM-CPP.DOBJ: BUILD/CCSYM-CPP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCSYM-GEN.S: B CCSYM.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCSYM.C
BUILD/CCSYM-GEN.DOBJ: BUILD/CCSYM-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCTYPE.S: B CCTYPE.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCTYPE.C
BUILD/CCTYPE.DOBJ: BUILD/CCTYPE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCTYPE-GEN.S: B CCTYPE.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCTYPE.C
BUILD/CCTYPE-GEN.DOBJ: BUILD/CCTYPE-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/CCVLA.S: B CCVLA.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H CCVLA.H
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) CCVLA.C
BUILD/CCVLA.DOBJ: BUILD/CCVLA.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/DAIMOS-CHAIN.S: B RUNTIME/DAIMOS-CHAIN.C

	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) RUNTIME/DAIMOS-CHAIN.C
BUILD/DAIMOS-CHAIN.DOBJ: BUILD/DAIMOS-CHAIN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/DAIMOS-PATH.S: B RUNTIME/DAIMOS-PATH.C

	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) RUNTIME/DAIMOS-PATH.C
BUILD/DAIMOS-PATH.DOBJ: BUILD/DAIMOS-PATH.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/DAIMOS-DRIVER.S: B RUNTIME/DAIMOS-DRIVER.C
	@/OPTION/BASE/EXEC/KCC -S -O $@ $(KCC_NATIVE_FLAGS) RUNTIME/DAIMOS-DRIVER.C
BUILD/DAIMOS-DRIVER.DOBJ: BUILD/DAIMOS-DRIVER.S
	@/OPTION/BASE/EXEC/DAS -F -C -O $@ $<
BUILD/KCC.DXR: BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ BUILD/DAIMOS-DRIVER.DOBJ \
    BOOT/LIBC.DARC
	@$(NATIVE_DLINK) --DAIMOS-UUO-RELAX -B 020 -O $@ $^
INSTALL: NATIVE
	@/SYSTEM/EXEC/INSTALL -D -M 0755 /OPTION/BASE/LIBEXEC/KCC
	@/SYSTEM/EXEC/INSTALL -M 0555 BUILD/KCPP.DXR /OPTION/BASE/LIBEXEC/KCC/KCPP
	@/SYSTEM/EXEC/INSTALL -M 0555 BUILD/KPARSE.DXR /OPTION/BASE/LIBEXEC/KCC/KPARSE
	@/SYSTEM/EXEC/INSTALL -M 0555 BUILD/KGEN.DXR /OPTION/BASE/LIBEXEC/KCC/KGEN
	@/SYSTEM/EXEC/INSTALL -M 0555 BUILD/KOPT.DXR /OPTION/BASE/LIBEXEC/KCC/KOPT
	@/SYSTEM/EXEC/INSTALL -M 0555 BUILD/KCC.DXR /OPTION/BASE/EXEC/KCC
CLEAN:
	-@$(NATIVE_RM) BUILD/DAIMOS-CHAIN.S BUILD/DAIMOS-CHAIN.DOBJ
	-@$(NATIVE_RM) BUILD/DAIMOS-PATH.S BUILD/DAIMOS-PATH.DOBJ
	-@$(NATIVE_RM) BUILD/CC-CPP.S BUILD/CC-CPP.DOBJ
	-@$(NATIVE_RM) BUILD/CC-PARSE.S BUILD/CC-PARSE.DOBJ
	-@$(NATIVE_RM) BUILD/CCASMB.S BUILD/CCASMB.DOBJ
	-@$(NATIVE_RM) BUILD/CCBIND-PARSE.S BUILD/CCBIND-PARSE.DOBJ
	-@$(NATIVE_RM) BUILD/CCCODE-GEN.S BUILD/CCCODE-GEN.DOBJ
	-@$(NATIVE_RM) BUILD/CCCREG.S BUILD/CCCREG.DOBJ
	-@$(NATIVE_RM) BUILD/CCCSE.S BUILD/CCCSE.DOBJ
	-@$(NATIVE_RM) BUILD/CCDATA-CPP.S BUILD/CCDATA-CPP.DOBJ
	-@$(NATIVE_RM) BUILD/CCDATA-GEN.S BUILD/CCDATA-GEN.DOBJ
	-@$(NATIVE_RM) BUILD/CCDATA-OPT.S BUILD/CCDATA-OPT.DOBJ
	-@$(NATIVE_RM) BUILD/CCDATA-PARSE.S BUILD/CCDATA-PARSE.DOBJ
	-@$(NATIVE_RM) BUILD/CCDBUG.S BUILD/CCDBUG.DOBJ
	-@$(NATIVE_RM) BUILD/CCDECL.S BUILD/CCDECL.DOBJ
	-@$(NATIVE_RM) BUILD/CCERR-CPP.S BUILD/CCERR-CPP.DOBJ
	-@$(NATIVE_RM) BUILD/CCERR-GEN.S BUILD/CCERR-GEN.DOBJ
	-@$(NATIVE_RM) BUILD/CCERR-OPT.S BUILD/CCERR-OPT.DOBJ
	-@$(NATIVE_RM) BUILD/CCERR-PARSE.S BUILD/CCERR-PARSE.DOBJ
	-@$(NATIVE_RM) BUILD/CCEVAL.S BUILD/CCEVAL.DOBJ
	-@$(NATIVE_RM) BUILD/CCEVALGEN.S BUILD/CCEVALGEN.DOBJ
	-@$(NATIVE_RM) BUILD/CCGEN-GEN.S BUILD/CCGEN-GEN.DOBJ
	-@$(NATIVE_RM) BUILD/CCGEN1-GEN.S BUILD/CCGEN1-GEN.DOBJ
	-@$(NATIVE_RM) BUILD/CCGEN2.S BUILD/CCGEN2.DOBJ
	-@$(NATIVE_RM) BUILD/CCGSWI.S BUILD/CCGSWI.DOBJ
	-@$(NATIVE_RM) BUILD/CCJSKP.S BUILD/CCJSKP.DOBJ
	-@$(NATIVE_RM) BUILD/CCKGEN-GEN.S BUILD/CCKGEN-GEN.DOBJ
	-@$(NATIVE_RM) BUILD/CCKIRREAD.S BUILD/CCKIRREAD.DOBJ
	-@$(NATIVE_RM) BUILD/CCKIRWRITE.S BUILD/CCKIRWRITE.DOBJ
	-@$(NATIVE_RM) BUILD/CCKOPT-OPT.S BUILD/CCKOPT-OPT.DOBJ
	-@$(NATIVE_RM) BUILD/CCKPOUT-GEN.S BUILD/CCKPOUT-GEN.DOBJ
	-@$(NATIVE_RM) BUILD/CCKPREAD-OPT.S BUILD/CCKPREAD-OPT.DOBJ
	-@$(NATIVE_RM) BUILD/CCKPWRITE-GEN.S BUILD/CCKPWRITE-GEN.DOBJ
	-@$(NATIVE_RM) BUILD/CCLEX.S BUILD/CCLEX.DOBJ
	-@$(NATIVE_RM) BUILD/CCNODE.S BUILD/CCNODE.DOBJ
	-@$(NATIVE_RM) BUILD/CCNODE-GEN.S BUILD/CCNODE-GEN.DOBJ
	-@$(NATIVE_RM) BUILD/CCOPT.S BUILD/CCOPT.DOBJ
	-@$(NATIVE_RM) BUILD/CCOUT-CPP.S BUILD/CCOUT-CPP.DOBJ
	-@$(NATIVE_RM) BUILD/CCOUT-OPT.S BUILD/CCOUT-OPT.DOBJ
	-@$(NATIVE_RM) BUILD/CCOUTUTIL.S BUILD/CCOUTUTIL.DOBJ
	-@$(NATIVE_RM) BUILD/CCPP.S BUILD/CCPP.DOBJ
	-@$(NATIVE_RM) BUILD/CCPPIN.S BUILD/CCPPIN.DOBJ
	-@$(NATIVE_RM) BUILD/CCPPOUT.S BUILD/CCPPOUT.DOBJ
	-@$(NATIVE_RM) BUILD/CCREG.S BUILD/CCREG.DOBJ
	-@$(NATIVE_RM) BUILD/CCSRC.S BUILD/CCSRC.DOBJ
	-@$(NATIVE_RM) BUILD/CCSTMT.S BUILD/CCSTMT.DOBJ
	-@$(NATIVE_RM) BUILD/CCSYM.S BUILD/CCSYM.DOBJ
	-@$(NATIVE_RM) BUILD/CCSYM-CPP.S BUILD/CCSYM-CPP.DOBJ
	-@$(NATIVE_RM) BUILD/CCSYM-GEN.S BUILD/CCSYM-GEN.DOBJ
	-@$(NATIVE_RM) BUILD/CCTYPE.S BUILD/CCTYPE.DOBJ
	-@$(NATIVE_RM) BUILD/CCTYPE-GEN.S BUILD/CCTYPE-GEN.DOBJ
	-@$(NATIVE_RM) BUILD/CCVLA.S BUILD/CCVLA.DOBJ
	-@$(NATIVE_RM) BUILD/DAIMOS-DRIVER.S BUILD/DAIMOS-DRIVER.DOBJ
	-@$(NATIVE_RM) BUILD/KCPP1.DARC
	-@$(NATIVE_RM) BUILD/KCPP2.DARC
	-@$(NATIVE_RM) BUILD/KCPP3.DARC
	-@$(NATIVE_RM) BUILD/KCPP.DXR
	-@$(NATIVE_RM) BUILD/KPARSE1.DARC
	-@$(NATIVE_RM) BUILD/KPARSE2.DARC
	-@$(NATIVE_RM) BUILD/KPARSE3.DARC
	-@$(NATIVE_RM) BUILD/KPARSE4.DARC
	-@$(NATIVE_RM) BUILD/KPARSE5.DARC
	-@$(NATIVE_RM) BUILD/KPARSE-RT.DARC
	-@$(NATIVE_RM) BUILD/KPARSE.DXR
	-@$(NATIVE_RM) BUILD/KGEN1.DARC
	-@$(NATIVE_RM) BUILD/KGEN2.DARC
	-@$(NATIVE_RM) BUILD/KGEN3.DARC
	-@$(NATIVE_RM) BUILD/KGEN4.DARC
	-@$(NATIVE_RM) BUILD/KGEN5.DARC
	-@$(NATIVE_RM) BUILD/KGEN6.DARC
	-@$(NATIVE_RM) BUILD/KGEN-RT.DARC
	-@$(NATIVE_RM) BUILD/KGEN.DXR
	-@$(NATIVE_RM) BUILD/KOPT1.DARC
	-@$(NATIVE_RM) BUILD/KOPT2.DARC
	-@$(NATIVE_RM) BUILD/KOPT-RT.DARC
	-@$(NATIVE_RM) BUILD/KOPT.DXR
	-@$(NATIVE_RM) BUILD/KCC.DXR
	-@/SYSTEM/EXEC/RMDIR BUILD
