# Native DAIMOS KCC build. Source and object inventory is in MAKEFILE.
# Keep prerequisites grouped in readable lines (about 96 characters);
# native MAKE accepts repeated target declarations.  Do not regenerate at boot.
NATIVE_BUILD_DIR = B
.PHONY: ALL INSTALL CLEAN KCPP KPARSE KGEN KOPT DRIVER
ALL: B KCPP KPARSE KGEN KOPT DRIVER
B:
	@/SYSTEM/EXEC/INSTALL -D -M 0777 B
B/KCPP1.DARC: B/CC-CPP.DOBJ B/CCASMB.DOBJ B/CCDATA-CPP.DOBJ B/CCERR-CPP.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KCPP1.DARC B/CC-CPP.DOBJ B/CCASMB.DOBJ B/CCDATA-CPP.DOBJ B/CCERR-CPP.DOBJ
B/KCPP2.DARC: B/CCOUT-CPP.DOBJ B/CCPP.DOBJ B/CCPPOUT.DOBJ B/CCSYM-CPP.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KCPP2.DARC B/CCOUT-CPP.DOBJ B/CCPP.DOBJ B/CCPPOUT.DOBJ B/CCSYM-CPP.DOBJ
B/KCPP3.DARC: B/CCSRC.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KCPP3.DARC B/CCSRC.DOBJ
B/KCPP.DXR: B/KCPP1.DARC B/KCPP2.DARC B/KCPP3.DARC BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ
B/KCPP.DXR: BOOT/HELP.DOBJ BOOT/LIBC.DARC
	@/OPTION/BASE/EXEC/DLINK --DAIMOS-UUO-RELAX -B 020 -O B/KCPP.DXR BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ B/KCPP1.DARC B/KCPP2.DARC B/KCPP3.DARC BOOT/LIBC.DARC
KCPP: B/KCPP.DXR
B/KPARSE1.DARC: B/CC-PARSE.DOBJ B/CCASMB.DOBJ B/CCDATA-PARSE.DOBJ B/CCBIND-PARSE.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KPARSE1.DARC B/CC-PARSE.DOBJ B/CCASMB.DOBJ B/CCDATA-PARSE.DOBJ B/CCBIND-PARSE.DOBJ
B/KPARSE2.DARC: B/CCDBUG.DOBJ B/CCDECL.DOBJ B/CCERR-PARSE.DOBJ B/CCEVAL.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KPARSE2.DARC B/CCDBUG.DOBJ B/CCDECL.DOBJ B/CCERR-PARSE.DOBJ B/CCEVAL.DOBJ
B/KPARSE3.DARC: B/CCLEX.DOBJ B/CCNODE.DOBJ B/CCPPIN.DOBJ B/CCSTMT.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KPARSE3.DARC B/CCLEX.DOBJ B/CCNODE.DOBJ B/CCPPIN.DOBJ B/CCSTMT.DOBJ
B/KPARSE4.DARC: B/CCSYM.DOBJ B/CCTYPE.DOBJ B/CCOUTUTIL.DOBJ B/CCKIRWRITE.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KPARSE4.DARC B/CCSYM.DOBJ B/CCTYPE.DOBJ B/CCOUTUTIL.DOBJ B/CCKIRWRITE.DOBJ
B/KPARSE5.DARC: B/CCVLA.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KPARSE5.DARC B/CCVLA.DOBJ
B/KPARSE-RT.DARC: B/DAIMOS-CHAIN.DOBJ B/DAIMOS-PATH.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KPARSE-RT.DARC B/DAIMOS-CHAIN.DOBJ B/DAIMOS-PATH.DOBJ
B/KPARSE.DXR: B/KPARSE1.DARC B/KPARSE2.DARC B/KPARSE3.DARC B/KPARSE4.DARC B/KPARSE5.DARC
B/KPARSE.DXR: B/KPARSE-RT.DARC BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ
B/KPARSE.DXR: BOOT/LIBC.DARC
	@/OPTION/BASE/EXEC/DLINK --DAIMOS-UUO-RELAX -B 020 -O B/KPARSE.DXR BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ B/KPARSE1.DARC B/KPARSE2.DARC B/KPARSE3.DARC B/KPARSE4.DARC B/KPARSE5.DARC B/KPARSE-RT.DARC BOOT/LIBC.DARC
KPARSE: B/KPARSE.DXR
B/KGEN1.DARC: B/CCKGEN-GEN.DOBJ B/CCCREG.DOBJ B/CCCSE.DOBJ B/CCCODE-GEN.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KGEN1.DARC B/CCKGEN-GEN.DOBJ B/CCCREG.DOBJ B/CCCSE.DOBJ B/CCCODE-GEN.DOBJ
B/KGEN2.DARC: B/CCDATA-GEN.DOBJ B/CCDBUG.DOBJ B/CCERR-GEN.DOBJ B/CCEVALGEN.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KGEN2.DARC B/CCDATA-GEN.DOBJ B/CCDBUG.DOBJ B/CCERR-GEN.DOBJ B/CCEVALGEN.DOBJ
B/KGEN3.DARC: B/CCGEN-GEN.DOBJ B/CCGEN1-GEN.DOBJ B/CCGEN2.DOBJ B/CCGSWI.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KGEN3.DARC B/CCGEN-GEN.DOBJ B/CCGEN1-GEN.DOBJ B/CCGEN2.DOBJ B/CCGSWI.DOBJ
B/KGEN4.DARC: B/CCJSKP.DOBJ B/CCNODE-GEN.DOBJ B/CCREG.DOBJ B/CCSYM-GEN.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KGEN4.DARC B/CCJSKP.DOBJ B/CCNODE-GEN.DOBJ B/CCREG.DOBJ B/CCSYM-GEN.DOBJ
B/KGEN5.DARC: B/CCTYPE-GEN.DOBJ B/CCOPT.DOBJ B/CCOUTUTIL.DOBJ B/CCKPOUT-GEN.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KGEN5.DARC B/CCTYPE-GEN.DOBJ B/CCOPT.DOBJ B/CCOUTUTIL.DOBJ B/CCKPOUT-GEN.DOBJ
B/KGEN6.DARC: B/CCKPWRITE-GEN.DOBJ B/CCKIRREAD.DOBJ B/CCVLA.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KGEN6.DARC B/CCKPWRITE-GEN.DOBJ B/CCKIRREAD.DOBJ B/CCVLA.DOBJ
B/KGEN-RT.DARC: B/DAIMOS-CHAIN.DOBJ B/DAIMOS-PATH.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KGEN-RT.DARC B/DAIMOS-CHAIN.DOBJ B/DAIMOS-PATH.DOBJ
B/KGEN.DXR: B/KGEN1.DARC B/KGEN2.DARC B/KGEN3.DARC B/KGEN4.DARC B/KGEN5.DARC B/KGEN6.DARC
B/KGEN.DXR: B/KGEN-RT.DARC BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ
B/KGEN.DXR: BOOT/LIBC.DARC
	@/OPTION/BASE/EXEC/DLINK --DAIMOS-UUO-RELAX -B 020 -O B/KGEN.DXR BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ B/KGEN1.DARC B/KGEN2.DARC B/KGEN3.DARC B/KGEN4.DARC B/KGEN5.DARC B/KGEN6.DARC B/KGEN-RT.DARC BOOT/LIBC.DARC
KGEN: B/KGEN.DXR
B/KOPT1.DARC: B/CCKOPT-OPT.DOBJ B/CCKPREAD-OPT.DOBJ B/CCOUT-OPT.DOBJ B/CCOUTUTIL.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KOPT1.DARC B/CCKOPT-OPT.DOBJ B/CCKPREAD-OPT.DOBJ B/CCOUT-OPT.DOBJ B/CCOUTUTIL.DOBJ
B/KOPT2.DARC: B/CCDATA-OPT.DOBJ B/CCERR-OPT.DOBJ B/CCASMB.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KOPT2.DARC B/CCDATA-OPT.DOBJ B/CCERR-OPT.DOBJ B/CCASMB.DOBJ
B/KOPT-RT.DARC: B/DAIMOS-PATH.DOBJ
	@/OPTION/BASE/EXEC/DARC -O B/KOPT-RT.DARC B/DAIMOS-PATH.DOBJ
B/KOPT.DXR: B/KOPT1.DARC B/KOPT2.DARC B/KOPT-RT.DARC BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ
B/KOPT.DXR: BOOT/HELP.DOBJ BOOT/LIBC.DARC
	@/OPTION/BASE/EXEC/DLINK --DAIMOS-UUO-RELAX -B 020 -O B/KOPT.DXR BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ B/KOPT1.DARC B/KOPT2.DARC B/KOPT-RT.DARC BOOT/LIBC.DARC
KOPT: B/KOPT.DXR
B/CC-CPP.S: B CC.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSITE.H CCSYM.H CCTOKS.H
B/CC-CPP.S: KCCHST.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CC-CPP.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_CPP=1 CC.C
B/CC-CPP.DOBJ: B/CC-CPP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CC-CPP.DOBJ B/CC-CPP.S
B/CC-PARSE.S: B CC.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSITE.H CCSYM.H CCTOKS.H
B/CC-PARSE.S: KCCHST.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CC-PARSE.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_PARSE=1 CC.C
B/CC-PARSE.DOBJ: B/CC-PARSE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CC-PARSE.DOBJ B/CC-PARSE.S
B/CCASMB.S: B CCASMB.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSITE.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCASMB.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCASMB.C
B/CCASMB.DOBJ: B/CCASMB.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCASMB.DOBJ B/CCASMB.S
B/CCBIND-PARSE.S: B CCBIND.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCBIND-PARSE.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_PARSE=1 CCBIND.C
B/CCBIND-PARSE.DOBJ: B/CCBIND-PARSE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCBIND-PARSE.DOBJ B/CCBIND-PARSE.S
B/CCCODE-GEN.S: B CCCODE.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H
B/CCCODE-GEN.S: CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCCODE-GEN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_GEN=1 CCCODE.C
B/CCCODE-GEN.DOBJ: B/CCCODE-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCCODE-GEN.DOBJ B/CCCODE-GEN.S
B/CCCREG.S: B CCCREG.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H CCSYM.H
B/CCCREG.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCCREG.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCCREG.C
B/CCCREG.DOBJ: B/CCCREG.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCCREG.DOBJ B/CCCREG.S
B/CCCSE.S: B CCCSE.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H CCSYM.H
B/CCCSE.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCCSE.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCCSE.C
B/CCCSE.DOBJ: B/CCCSE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCCSE.DOBJ B/CCCSE.S
B/CCDATA-CPP.S: B CCDATA.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCLEX.H CCNODE.H
B/CCDATA-CPP.S: CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCDATA-CPP.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_CPP=1 CCDATA.C
B/CCDATA-CPP.DOBJ: B/CCDATA-CPP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCDATA-CPP.DOBJ B/CCDATA-CPP.S
B/CCDATA-GEN.S: B CCDATA.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCLEX.H CCNODE.H
B/CCDATA-GEN.S: CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCDATA-GEN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_GEN=1 CCDATA.C
B/CCDATA-GEN.DOBJ: B/CCDATA-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCDATA-GEN.DOBJ B/CCDATA-GEN.S
B/CCDATA-OPT.S: B CCDATA.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCLEX.H CCNODE.H
B/CCDATA-OPT.S: CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCDATA-OPT.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_OPT=1 CCDATA.C
B/CCDATA-OPT.DOBJ: B/CCDATA-OPT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCDATA-OPT.DOBJ B/CCDATA-OPT.S
B/CCDATA-PARSE.S: B CCDATA.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCLEX.H CCNODE.H
B/CCDATA-PARSE.S: CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCDATA-PARSE.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_PARSE=1 CCDATA.C
B/CCDATA-PARSE.DOBJ: B/CCDATA-PARSE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCDATA-PARSE.DOBJ B/CCDATA-PARSE.S
B/CCDBUG.S: B CCDBUG.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H CCSYM.H
B/CCDBUG.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCDBUG.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCDBUG.C
B/CCDBUG.DOBJ: B/CCDBUG.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCDBUG.DOBJ B/CCDBUG.S
B/CCDECL.S: B CCDECL.C C-ENV.H CC.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H CCVLA.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCDECL.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCDECL.C
B/CCDECL.DOBJ: B/CCDECL.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCDECL.DOBJ B/CCDECL.S
B/CCERR-CPP.S: B CCERR.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H
B/CCERR-CPP.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCERR-CPP.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_CPP=1 CCERR.C
B/CCERR-CPP.DOBJ: B/CCERR-CPP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCERR-CPP.DOBJ B/CCERR-CPP.S
B/CCERR-GEN.S: B CCERR.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H
B/CCERR-GEN.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCERR-GEN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_GEN=1 CCERR.C
B/CCERR-GEN.DOBJ: B/CCERR-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCERR-GEN.DOBJ B/CCERR-GEN.S
B/CCERR-OPT.S: B CCERR.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H
B/CCERR-OPT.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCERR-OPT.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_OPT=1 CCERR.C
B/CCERR-OPT.DOBJ: B/CCERR-OPT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCERR-OPT.DOBJ B/CCERR-OPT.S
B/CCERR-PARSE.S: B CCERR.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H
B/CCERR-PARSE.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCERR-PARSE.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_PARSE=1 CCERR.C
B/CCERR-PARSE.DOBJ: B/CCERR-PARSE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCERR-PARSE.DOBJ B/CCERR-PARSE.S
B/CCEVAL.S: B CCEVAL.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCEVAL.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCEVAL.C
B/CCEVAL.DOBJ: B/CCEVAL.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCEVAL.DOBJ B/CCEVAL.S
B/CCEVALGEN.S: B CCEVALGEN.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCEVALGEN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCEVALGEN.C
B/CCEVALGEN.DOBJ: B/CCEVALGEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCEVALGEN.DOBJ B/CCEVALGEN.S
B/CCGEN-GEN.S: B CCGEN.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H
B/CCGEN-GEN.S: CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCGEN-GEN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_GEN=1 CCGEN.C
B/CCGEN-GEN.DOBJ: B/CCGEN-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCGEN-GEN.DOBJ B/CCGEN-GEN.S
B/CCGEN1-GEN.S: B CCGEN1.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H
B/CCGEN1-GEN.S: CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCGEN1-GEN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_GEN=1 CCGEN1.C
B/CCGEN1-GEN.DOBJ: B/CCGEN1-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCGEN1-GEN.DOBJ B/CCGEN1-GEN.S
B/CCGEN2.S: B CCGEN2.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H CCSYM.H
B/CCGEN2.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCGEN2.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCGEN2.C
B/CCGEN2.DOBJ: B/CCGEN2.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCGEN2.DOBJ B/CCGEN2.S
B/CCGSWI.S: B CCGSWI.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H CCSYM.H
B/CCGSWI.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCGSWI.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCGSWI.C
B/CCGSWI.DOBJ: B/CCGSWI.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCGSWI.DOBJ B/CCGSWI.S
B/CCJSKP.S: B CCJSKP.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H CCSYM.H
B/CCJSKP.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCJSKP.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCJSKP.C
B/CCJSKP.DOBJ: B/CCJSKP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCJSKP.DOBJ B/CCJSKP.S
B/CCKGEN-GEN.S: B CCKGEN.C C-ENV.H CC.H CCERR.H CCKIR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCKGEN-GEN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_GEN=1 CCKGEN.C
B/CCKGEN-GEN.DOBJ: B/CCKGEN-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCKGEN-GEN.DOBJ B/CCKGEN-GEN.S
B/CCKIRREAD.S: B CCKIRREAD.C C-ENV.H CC.H CCERR.H CCKIR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
B/CCKIRREAD.S: CCVLA.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCKIRREAD.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCKIRREAD.C
B/CCKIRREAD.DOBJ: B/CCKIRREAD.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCKIRREAD.DOBJ B/CCKIRREAD.S
B/CCKIRWRITE.S: B CCKIRWRITE.C C-ENV.H CC.H CCERR.H CCKIR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
B/CCKIRWRITE.S: CCVLA.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCKIRWRITE.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCKIRWRITE.C
B/CCKIRWRITE.DOBJ: B/CCKIRWRITE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCKIRWRITE.DOBJ B/CCKIRWRITE.S
B/CCKOPT-OPT.S: B CCKOPT.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCKPCODE.H CCNODE.H CCPARM.H
B/CCKOPT-OPT.S: CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCKOPT-OPT.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_OPT=1 CCKOPT.C
B/CCKOPT-OPT.DOBJ: B/CCKOPT-OPT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCKOPT-OPT.DOBJ B/CCKOPT-OPT.S
B/CCKPOUT-GEN.S: B CCKPOUT.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCKPCODE.H CCNODE.H CCPARM.H
B/CCKPOUT-GEN.S: CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCKPOUT-GEN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_GEN=1 CCKPOUT.C
B/CCKPOUT-GEN.DOBJ: B/CCKPOUT-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCKPOUT-GEN.DOBJ B/CCKPOUT-GEN.S
B/CCKPREAD-OPT.S: B CCKPREAD.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCKPCODE.H CCNODE.H
B/CCKPREAD-OPT.S: CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCKPREAD-OPT.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_OPT=1 CCKPREAD.C
B/CCKPREAD-OPT.DOBJ: B/CCKPREAD-OPT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCKPREAD-OPT.DOBJ B/CCKPREAD-OPT.S
B/CCKPWRITE-GEN.S: B CCKPWRITE.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCKPCODE.H CCNODE.H
B/CCKPWRITE-GEN.S: CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCKPWRITE-GEN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_GEN=1 CCKPWRITE.C
B/CCKPWRITE-GEN.DOBJ: B/CCKPWRITE-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCKPWRITE-GEN.DOBJ B/CCKPWRITE-GEN.S
B/CCLEX.S: B CCLEX.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCLEX.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCLEX.C
B/CCLEX.DOBJ: B/CCLEX.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCLEX.DOBJ B/CCLEX.S
B/CCNODE.S: B CCNODE.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCNODE.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCNODE.C
B/CCNODE.DOBJ: B/CCNODE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCNODE.DOBJ B/CCNODE.S
B/CCNODE-GEN.S: B CCNODE.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCNODE-GEN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_GEN=1 CCNODE.C
B/CCNODE-GEN.DOBJ: B/CCNODE-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCNODE-GEN.DOBJ B/CCNODE-GEN.S
B/CCOPT.S: B CCOPT.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H CCSYM.H
B/CCOPT.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCOPT.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCOPT.C
B/CCOPT.DOBJ: B/CCOPT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCOPT.DOBJ B/CCOPT.S
B/CCOUT-CPP.S: B CCOUT.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H
B/CCOUT-CPP.S: CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCOUT-CPP.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_CPP=1 CCOUT.C
B/CCOUT-CPP.DOBJ: B/CCOUT-CPP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCOUT-CPP.DOBJ B/CCOUT-CPP.S
B/CCOUT-OPT.S: B CCOUT.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H
B/CCOUT-OPT.S: CCREG.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCOUT-OPT.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_OPT=1 CCOUT.C
B/CCOUT-OPT.DOBJ: B/CCOUT-OPT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCOUT-OPT.DOBJ B/CCOUT-OPT.S
B/CCOUTUTIL.S: B CCOUTUTIL.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H
B/CCOUTUTIL.S: CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCOUTUTIL.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCOUTUTIL.C
B/CCOUTUTIL.DOBJ: B/CCOUTUTIL.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCOUTUTIL.DOBJ B/CCOUTUTIL.S
B/CCPP.S: B CCPP.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSRC.H CCSYM.H
B/CCPP.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCPP.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCPP.C
B/CCPP.DOBJ: B/CCPP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCPP.DOBJ B/CCPP.S
B/CCPPIN.S: B CCPPIN.C C-ENV.H CC.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCPHASE.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCPPIN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCPPIN.C
B/CCPPIN.DOBJ: B/CCPPIN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCPPIN.DOBJ B/CCPPIN.S
B/CCPPOUT.S: B CCPPOUT.C C-ENV.H CC.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCPHASE.H CCSYM.H
B/CCPPOUT.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCPPOUT.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCPPOUT.C
B/CCPPOUT.DOBJ: B/CCPPOUT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCPPOUT.DOBJ B/CCPPOUT.S
B/CCREG.S: B CCREG.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H CCSYM.H
B/CCREG.S: CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCREG.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCREG.C
B/CCREG.DOBJ: B/CCREG.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCREG.DOBJ B/CCREG.S
B/CCSRC.S: B CCSRC.C CCSRC.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCSRC.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCSRC.C
B/CCSRC.DOBJ: B/CCSRC.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCSRC.DOBJ B/CCSRC.S
B/CCSTMT.S: B CCSTMT.C C-ENV.H CC.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCSTMT.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCSTMT.C
B/CCSTMT.DOBJ: B/CCSTMT.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCSTMT.DOBJ B/CCSTMT.S
B/CCSYM.S: B CCSYM.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCSYM.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCSYM.C
B/CCSYM.DOBJ: B/CCSYM.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCSYM.DOBJ B/CCSYM.S
B/CCSYM-CPP.S: B CCSYM.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCSYM-CPP.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_CPP=1 CCSYM.C
B/CCSYM-CPP.DOBJ: B/CCSYM-CPP.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCSYM-CPP.DOBJ B/CCSYM-CPP.S
B/CCSYM-GEN.S: B CCSYM.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCSYM-GEN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_GEN=1 CCSYM.C
B/CCSYM-GEN.DOBJ: B/CCSYM-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCSYM-GEN.DOBJ B/CCSYM-GEN.S
B/CCTYPE.S: B CCTYPE.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCTYPE.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCTYPE.C
B/CCTYPE.DOBJ: B/CCTYPE.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCTYPE.DOBJ B/CCTYPE.S
B/CCTYPE-GEN.S: B CCTYPE.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCTYPE-GEN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI -DKCC_PHASE_GEN=1 CCTYPE.C
B/CCTYPE-GEN.DOBJ: B/CCTYPE-GEN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCTYPE-GEN.DOBJ B/CCTYPE-GEN.S
B/CCVLA.S: B CCVLA.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H CCVLA.H
	@/OPTION/BASE/EXEC/KCC -S -O B/CCVLA.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI CCVLA.C
B/CCVLA.DOBJ: B/CCVLA.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/CCVLA.DOBJ B/CCVLA.S
B/DAIMOS-CHAIN.S: B RUNTIME/DAIMOS-CHAIN.C

	@/OPTION/BASE/EXEC/KCC -S -O B/DAIMOS-CHAIN.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI RUNTIME/DAIMOS-CHAIN.C
B/DAIMOS-CHAIN.DOBJ: B/DAIMOS-CHAIN.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/DAIMOS-CHAIN.DOBJ B/DAIMOS-CHAIN.S
B/DAIMOS-PATH.S: B RUNTIME/DAIMOS-PATH.C

	@/OPTION/BASE/EXEC/KCC -S -O B/DAIMOS-PATH.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI RUNTIME/DAIMOS-PATH.C
B/DAIMOS-PATH.DOBJ: B/DAIMOS-PATH.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/DAIMOS-PATH.DOBJ B/DAIMOS-PATH.S
B/DAIMOS-DRIVER.S: B RUNTIME/DAIMOS-DRIVER.C
	@/OPTION/BASE/EXEC/KCC -S -O B/DAIMOS-DRIVER.S -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI RUNTIME/DAIMOS-DRIVER.C
B/DAIMOS-DRIVER.DOBJ: B/DAIMOS-DRIVER.S
	@/OPTION/BASE/EXEC/DAS -F -C -O B/DAIMOS-DRIVER.DOBJ B/DAIMOS-DRIVER.S
B/KCC.DXR: B/DAIMOS-DRIVER.DOBJ BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ
B/KCC.DXR: BOOT/LIBC.DARC
	@/OPTION/BASE/EXEC/DLINK --DAIMOS-UUO-RELAX -B 020 -O B/KCC.DXR BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ B/DAIMOS-DRIVER.DOBJ BOOT/LIBC.DARC
DRIVER: B/KCC.DXR
INSTALL: ALL
	@/SYSTEM/EXEC/INSTALL -D -M 0755 /OPTION/BASE/LIBEXEC/KCC
	@/SYSTEM/EXEC/INSTALL -M 0555 B/KCPP.DXR /OPTION/BASE/LIBEXEC/KCC/KCPP
	@/SYSTEM/EXEC/INSTALL -M 0555 B/KPARSE.DXR /OPTION/BASE/LIBEXEC/KCC/KPARSE
	@/SYSTEM/EXEC/INSTALL -M 0555 B/KGEN.DXR /OPTION/BASE/LIBEXEC/KCC/KGEN
	@/SYSTEM/EXEC/INSTALL -M 0555 B/KOPT.DXR /OPTION/BASE/LIBEXEC/KCC/KOPT
	@/SYSTEM/EXEC/INSTALL -M 0555 B/KCC.DXR /OPTION/BASE/EXEC/KCC
CLEAN:
	-@/SYSTEM/EXEC/RM B/DAIMOS-CHAIN.S
	-@/SYSTEM/EXEC/RM B/DAIMOS-CHAIN.DOBJ
	-@/SYSTEM/EXEC/RM B/DAIMOS-PATH.S
	-@/SYSTEM/EXEC/RM B/DAIMOS-PATH.DOBJ
	-@/SYSTEM/EXEC/RM B/CC-CPP.S
	-@/SYSTEM/EXEC/RM B/CC-CPP.DOBJ
	-@/SYSTEM/EXEC/RM B/CC-PARSE.S
	-@/SYSTEM/EXEC/RM B/CC-PARSE.DOBJ
	-@/SYSTEM/EXEC/RM B/CCASMB.S
	-@/SYSTEM/EXEC/RM B/CCASMB.DOBJ
	-@/SYSTEM/EXEC/RM B/CCBIND-PARSE.S
	-@/SYSTEM/EXEC/RM B/CCBIND-PARSE.DOBJ
	-@/SYSTEM/EXEC/RM B/CCCODE-GEN.S
	-@/SYSTEM/EXEC/RM B/CCCODE-GEN.DOBJ
	-@/SYSTEM/EXEC/RM B/CCCREG.S
	-@/SYSTEM/EXEC/RM B/CCCREG.DOBJ
	-@/SYSTEM/EXEC/RM B/CCCSE.S
	-@/SYSTEM/EXEC/RM B/CCCSE.DOBJ
	-@/SYSTEM/EXEC/RM B/CCDATA-CPP.S
	-@/SYSTEM/EXEC/RM B/CCDATA-CPP.DOBJ
	-@/SYSTEM/EXEC/RM B/CCDATA-GEN.S
	-@/SYSTEM/EXEC/RM B/CCDATA-GEN.DOBJ
	-@/SYSTEM/EXEC/RM B/CCDATA-OPT.S
	-@/SYSTEM/EXEC/RM B/CCDATA-OPT.DOBJ
	-@/SYSTEM/EXEC/RM B/CCDATA-PARSE.S
	-@/SYSTEM/EXEC/RM B/CCDATA-PARSE.DOBJ
	-@/SYSTEM/EXEC/RM B/CCDBUG.S
	-@/SYSTEM/EXEC/RM B/CCDBUG.DOBJ
	-@/SYSTEM/EXEC/RM B/CCDECL.S
	-@/SYSTEM/EXEC/RM B/CCDECL.DOBJ
	-@/SYSTEM/EXEC/RM B/CCERR-CPP.S
	-@/SYSTEM/EXEC/RM B/CCERR-CPP.DOBJ
	-@/SYSTEM/EXEC/RM B/CCERR-GEN.S
	-@/SYSTEM/EXEC/RM B/CCERR-GEN.DOBJ
	-@/SYSTEM/EXEC/RM B/CCERR-OPT.S
	-@/SYSTEM/EXEC/RM B/CCERR-OPT.DOBJ
	-@/SYSTEM/EXEC/RM B/CCERR-PARSE.S
	-@/SYSTEM/EXEC/RM B/CCERR-PARSE.DOBJ
	-@/SYSTEM/EXEC/RM B/CCEVAL.S
	-@/SYSTEM/EXEC/RM B/CCEVAL.DOBJ
	-@/SYSTEM/EXEC/RM B/CCEVALGEN.S
	-@/SYSTEM/EXEC/RM B/CCEVALGEN.DOBJ
	-@/SYSTEM/EXEC/RM B/CCGEN-GEN.S
	-@/SYSTEM/EXEC/RM B/CCGEN-GEN.DOBJ
	-@/SYSTEM/EXEC/RM B/CCGEN1-GEN.S
	-@/SYSTEM/EXEC/RM B/CCGEN1-GEN.DOBJ
	-@/SYSTEM/EXEC/RM B/CCGEN2.S
	-@/SYSTEM/EXEC/RM B/CCGEN2.DOBJ
	-@/SYSTEM/EXEC/RM B/CCGSWI.S
	-@/SYSTEM/EXEC/RM B/CCGSWI.DOBJ
	-@/SYSTEM/EXEC/RM B/CCJSKP.S
	-@/SYSTEM/EXEC/RM B/CCJSKP.DOBJ
	-@/SYSTEM/EXEC/RM B/CCKGEN-GEN.S
	-@/SYSTEM/EXEC/RM B/CCKGEN-GEN.DOBJ
	-@/SYSTEM/EXEC/RM B/CCKIRREAD.S
	-@/SYSTEM/EXEC/RM B/CCKIRREAD.DOBJ
	-@/SYSTEM/EXEC/RM B/CCKIRWRITE.S
	-@/SYSTEM/EXEC/RM B/CCKIRWRITE.DOBJ
	-@/SYSTEM/EXEC/RM B/CCKOPT-OPT.S
	-@/SYSTEM/EXEC/RM B/CCKOPT-OPT.DOBJ
	-@/SYSTEM/EXEC/RM B/CCKPOUT-GEN.S
	-@/SYSTEM/EXEC/RM B/CCKPOUT-GEN.DOBJ
	-@/SYSTEM/EXEC/RM B/CCKPREAD-OPT.S
	-@/SYSTEM/EXEC/RM B/CCKPREAD-OPT.DOBJ
	-@/SYSTEM/EXEC/RM B/CCKPWRITE-GEN.S
	-@/SYSTEM/EXEC/RM B/CCKPWRITE-GEN.DOBJ
	-@/SYSTEM/EXEC/RM B/CCLEX.S
	-@/SYSTEM/EXEC/RM B/CCLEX.DOBJ
	-@/SYSTEM/EXEC/RM B/CCNODE.S
	-@/SYSTEM/EXEC/RM B/CCNODE.DOBJ
	-@/SYSTEM/EXEC/RM B/CCNODE-GEN.S
	-@/SYSTEM/EXEC/RM B/CCNODE-GEN.DOBJ
	-@/SYSTEM/EXEC/RM B/CCOPT.S
	-@/SYSTEM/EXEC/RM B/CCOPT.DOBJ
	-@/SYSTEM/EXEC/RM B/CCOUT-CPP.S
	-@/SYSTEM/EXEC/RM B/CCOUT-CPP.DOBJ
	-@/SYSTEM/EXEC/RM B/CCOUT-OPT.S
	-@/SYSTEM/EXEC/RM B/CCOUT-OPT.DOBJ
	-@/SYSTEM/EXEC/RM B/CCOUTUTIL.S
	-@/SYSTEM/EXEC/RM B/CCOUTUTIL.DOBJ
	-@/SYSTEM/EXEC/RM B/CCPP.S
	-@/SYSTEM/EXEC/RM B/CCPP.DOBJ
	-@/SYSTEM/EXEC/RM B/CCPPIN.S
	-@/SYSTEM/EXEC/RM B/CCPPIN.DOBJ
	-@/SYSTEM/EXEC/RM B/CCPPOUT.S
	-@/SYSTEM/EXEC/RM B/CCPPOUT.DOBJ
	-@/SYSTEM/EXEC/RM B/CCREG.S
	-@/SYSTEM/EXEC/RM B/CCREG.DOBJ
	-@/SYSTEM/EXEC/RM B/CCSRC.S
	-@/SYSTEM/EXEC/RM B/CCSRC.DOBJ
	-@/SYSTEM/EXEC/RM B/CCSTMT.S
	-@/SYSTEM/EXEC/RM B/CCSTMT.DOBJ
	-@/SYSTEM/EXEC/RM B/CCSYM.S
	-@/SYSTEM/EXEC/RM B/CCSYM.DOBJ
	-@/SYSTEM/EXEC/RM B/CCSYM-CPP.S
	-@/SYSTEM/EXEC/RM B/CCSYM-CPP.DOBJ
	-@/SYSTEM/EXEC/RM B/CCSYM-GEN.S
	-@/SYSTEM/EXEC/RM B/CCSYM-GEN.DOBJ
	-@/SYSTEM/EXEC/RM B/CCTYPE.S
	-@/SYSTEM/EXEC/RM B/CCTYPE.DOBJ
	-@/SYSTEM/EXEC/RM B/CCTYPE-GEN.S
	-@/SYSTEM/EXEC/RM B/CCTYPE-GEN.DOBJ
	-@/SYSTEM/EXEC/RM B/CCVLA.S
	-@/SYSTEM/EXEC/RM B/CCVLA.DOBJ
	-@/SYSTEM/EXEC/RM B/DAIMOS-DRIVER.S
	-@/SYSTEM/EXEC/RM B/DAIMOS-DRIVER.DOBJ
	-@/SYSTEM/EXEC/RM B/KCPP1.DARC
	-@/SYSTEM/EXEC/RM B/KCPP2.DARC
	-@/SYSTEM/EXEC/RM B/KCPP3.DARC
	-@/SYSTEM/EXEC/RM B/KCPP.DXR
	-@/SYSTEM/EXEC/RM B/KPARSE1.DARC
	-@/SYSTEM/EXEC/RM B/KPARSE2.DARC
	-@/SYSTEM/EXEC/RM B/KPARSE3.DARC
	-@/SYSTEM/EXEC/RM B/KPARSE4.DARC
	-@/SYSTEM/EXEC/RM B/KPARSE5.DARC
	-@/SYSTEM/EXEC/RM B/KPARSE-RT.DARC
	-@/SYSTEM/EXEC/RM B/KPARSE.DXR
	-@/SYSTEM/EXEC/RM B/KGEN1.DARC
	-@/SYSTEM/EXEC/RM B/KGEN2.DARC
	-@/SYSTEM/EXEC/RM B/KGEN3.DARC
	-@/SYSTEM/EXEC/RM B/KGEN4.DARC
	-@/SYSTEM/EXEC/RM B/KGEN5.DARC
	-@/SYSTEM/EXEC/RM B/KGEN6.DARC
	-@/SYSTEM/EXEC/RM B/KGEN-RT.DARC
	-@/SYSTEM/EXEC/RM B/KGEN.DXR
	-@/SYSTEM/EXEC/RM B/KOPT1.DARC
	-@/SYSTEM/EXEC/RM B/KOPT2.DARC
	-@/SYSTEM/EXEC/RM B/KOPT-RT.DARC
	-@/SYSTEM/EXEC/RM B/KOPT.DXR
	-@/SYSTEM/EXEC/RM B/KCC.DXR
