# Native DAIMOS KCC build. Generated files are kept in BUILD/.
# Keep prerequisites grouped in readable lines (about 96 characters);
# use portable backslash continuations within the 256-character logical-line
# limit of native MAKE.  Do not regenerate at boot.
NATIVE_BUILD_DIR = BUILD
KCC_NATIVE_FLAGS = -Pgnu99 -x=pdp6 -m=gas -DHOST_DAIMOS=1 -DHOST_UNIX=0 -I/OPTION/SOURCE/KCC/SELF/INCLUDE -I/OPTION/SOURCE/KCC/ABI
# Archive and DLINK recipes use ordered prerequisites with $^.
# DLINK dependencies put startup objects before phase archives.
NATIVE_DARC = $(NATIVE_EXEC)/DARC
NATIVE_DLINK = $(NATIVE_EXEC)/DLINK
NATIVE_RM = /SYSTEM/EXEC/RM
NATIVE_EXEC = /OPTION/BASE/EXEC
NATIVE_KCC = $(NATIVE_EXEC)/KCC
NATIVE_DAS = $(NATIVE_EXEC)/DAS
NATIVE_INSTALL = /SYSTEM/EXEC/INSTALL
NATIVE_KCC_LIBEXEC = /OPTION/BASE/LIBEXEC/KCC
.SUFFIXES: .S .DOBJ
.S.DOBJ:
	@$(NATIVE_DAS) -F -C -O $@ $<
.PHONY: NATIVE INSTALL CLEAN
NATIVE: BUILD BUILD/KCPP.DXR BUILD/KPARSE.DXR BUILD/KGEN.DXR BUILD/KOPT.DXR BUILD/KCC.DXR
BUILD:
	@$(NATIVE_INSTALL) -D -M 0777 BUILD
BUILD/KCPP1.DARC: BUILD/CC-CPP.DOBJ BUILD/CCASMB.DOBJ BUILD/CCDATA-CPP.DOBJ BUILD/CCERR-CPP.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KCPP2.DARC: BUILD/CCOUT-CPP.DOBJ BUILD/CCPP.DOBJ BUILD/CCPPOUT.DOBJ BUILD/CCSYM-CPP.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KCPP3.DARC: BUILD/CCSRC.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KCPP.DXR: BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ BUILD/KCPP1.DARC \
    BUILD/KCPP2.DARC BUILD/KCPP3.DARC BOOT/LIBC.DARC
	@$(NATIVE_DLINK) --DAIMOS-UUO-RELAX -B 020 -O $@ $^
BUILD/KPARSE1.DARC: BUILD/CC-PARSE.DOBJ BUILD/CCASMB.DOBJ BUILD/CCDATA-PARSE.DOBJ BUILD/CCBIND-PARSE.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KPARSE2.DARC: BUILD/CCDBUG.DOBJ BUILD/CCDECL.DOBJ BUILD/CCERR-PARSE.DOBJ BUILD/CCEVAL.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KPARSE3.DARC: BUILD/CCLEX.DOBJ BUILD/CCNODE.DOBJ BUILD/CCPPIN.DOBJ BUILD/CCSTMT.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KPARSE4.DARC: BUILD/CCSYM.DOBJ BUILD/CCTYPE.DOBJ BUILD/CCOUTUTIL.DOBJ BUILD/CCKIRWRITE.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KPARSE5.DARC: BUILD/CCVLA.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KPARSE-RT.DARC: BUILD/DAIMOS-CHAIN.DOBJ BUILD/DAIMOS-PATH.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KPARSE.DXR: BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ BUILD/KPARSE1.DARC \
    BUILD/KPARSE2.DARC BUILD/KPARSE3.DARC BUILD/KPARSE4.DARC BUILD/KPARSE5.DARC BUILD/KPARSE-RT.DARC \
    BOOT/LIBC.DARC
	@$(NATIVE_DLINK) --DAIMOS-UUO-RELAX -B 020 -O $@ $^
BUILD/KGEN1.DARC: BUILD/CCKGEN-GEN.DOBJ BUILD/CCCREG.DOBJ BUILD/CCCSE.DOBJ BUILD/CCCODE-GEN.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN2.DARC: BUILD/CCDATA-GEN.DOBJ BUILD/CCDBUG.DOBJ BUILD/CCERR-GEN.DOBJ BUILD/CCEVALGEN.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN3.DARC: BUILD/CCGEN-GEN.DOBJ BUILD/CCGEN1-GEN.DOBJ BUILD/CCGEN2.DOBJ BUILD/CCGSWI.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN4.DARC: BUILD/CCJSKP.DOBJ BUILD/CCNODE-GEN.DOBJ BUILD/CCREG.DOBJ BUILD/CCSYM-GEN.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN5.DARC: BUILD/CCTYPE-GEN.DOBJ BUILD/CCOPT.DOBJ BUILD/CCOUTUTIL.DOBJ BUILD/CCKPOUT-GEN.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN6.DARC: BUILD/CCKPWRITE-GEN.DOBJ BUILD/CCKIRREAD.DOBJ BUILD/CCVLA.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN-RT.DARC: BUILD/DAIMOS-CHAIN.DOBJ BUILD/DAIMOS-PATH.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KGEN.DXR: BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ BUILD/KGEN1.DARC \
    BUILD/KGEN2.DARC BUILD/KGEN3.DARC BUILD/KGEN4.DARC BUILD/KGEN5.DARC BUILD/KGEN6.DARC BUILD/KGEN-RT.DARC \
    BOOT/LIBC.DARC
	@$(NATIVE_DLINK) --DAIMOS-UUO-RELAX -B 020 -O $@ $^
BUILD/KOPT1.DARC: BUILD/CCKOPT-OPT.DOBJ BUILD/CCKPREAD-OPT.DOBJ BUILD/CCOUT-OPT.DOBJ BUILD/CCOUTUTIL.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KOPT2.DARC: BUILD/CCDATA-OPT.DOBJ BUILD/CCERR-OPT.DOBJ BUILD/CCASMB.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KOPT-RT.DARC: BUILD/DAIMOS-PATH.DOBJ
	@$(NATIVE_DARC) -O $@ $^
BUILD/KOPT.DXR: BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ BUILD/KOPT1.DARC \
    BUILD/KOPT2.DARC BUILD/KOPT-RT.DARC BOOT/LIBC.DARC
	@$(NATIVE_DLINK) --DAIMOS-UUO-RELAX -B 020 -O $@ $^
BUILD/CC-CPP.S: BUILD CC.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSITE.H CCSYM.H \
    CCTOKS.H KCCHST.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_CPP=1 CC.C
BUILD/CC-PARSE.S: BUILD CC.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSITE.H CCSYM.H \
    CCTOKS.H KCCHST.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_PARSE=1 CC.C
BUILD/CCASMB.S: BUILD CCASMB.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSITE.H CCSYM.H \
    CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCASMB.C
BUILD/CCBIND-PARSE.S: BUILD CCBIND.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_PARSE=1 CCBIND.C
BUILD/CCCODE-GEN.S: BUILD CCCODE.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H \
    CCREG.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCCODE.C
BUILD/CCCREG.S: BUILD CCCREG.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCCREG.C
BUILD/CCCSE.S: BUILD CCCSE.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCCSE.C
BUILD/CCDATA-CPP.S: BUILD CCDATA.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCLEX.H \
    CCNODE.H CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_CPP=1 CCDATA.C
BUILD/CCDATA-GEN.S: BUILD CCDATA.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCLEX.H \
    CCNODE.H CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCDATA.C
BUILD/CCDATA-OPT.S: BUILD CCDATA.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCLEX.H \
    CCNODE.H CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_OPT=1 CCDATA.C
BUILD/CCDATA-PARSE.S: BUILD CCDATA.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCLEX.H \
    CCNODE.H CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_PARSE=1 CCDATA.C
BUILD/CCDBUG.S: BUILD CCDBUG.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCDBUG.C
BUILD/CCDECL.S: BUILD CCDECL.C C-ENV.H CC.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H \
    CCVLA.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCDECL.C
BUILD/CCERR-CPP.S: BUILD CCERR.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_CPP=1 CCERR.C
BUILD/CCERR-GEN.S: BUILD CCERR.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCERR.C
BUILD/CCERR-OPT.S: BUILD CCERR.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_OPT=1 CCERR.C
BUILD/CCERR-PARSE.S: BUILD CCERR.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H \
    CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_PARSE=1 CCERR.C
BUILD/CCEVAL.S: BUILD CCEVAL.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCEVAL.C
BUILD/CCEVALGEN.S: BUILD CCEVALGEN.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCEVALGEN.C
BUILD/CCGEN-GEN.S: BUILD CCGEN.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCNODE.H \
    CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCGEN.C
BUILD/CCGEN1-GEN.S: BUILD CCGEN1.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H \
    CCREG.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCGEN1.C
BUILD/CCGEN2.S: BUILD CCGEN2.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCGEN2.C
BUILD/CCGSWI.S: BUILD CCGSWI.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCGSWI.C
BUILD/CCJSKP.S: BUILD CCJSKP.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCJSKP.C
BUILD/CCKGEN-GEN.S: BUILD CCKGEN.C C-ENV.H CC.H CCERR.H CCKIR.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCKGEN.C
BUILD/CCKIRREAD.S: BUILD CCKIRREAD.C C-ENV.H CC.H CCERR.H CCKIR.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H CCVLA.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCKIRREAD.C
BUILD/CCKIRWRITE.S: BUILD CCKIRWRITE.C C-ENV.H CC.H CCERR.H CCKIR.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H CCVLA.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCKIRWRITE.C
BUILD/CCKOPT-OPT.S: BUILD CCKOPT.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCKPCODE.H CCNODE.H \
    CCPARM.H CCREG.H CCSITE.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_OPT=1 CCKOPT.C
BUILD/CCKPOUT-GEN.S: BUILD CCKPOUT.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCKPCODE.H CCNODE.H \
    CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCKPOUT.C
BUILD/CCKPREAD-OPT.S: BUILD CCKPREAD.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCKPCODE.H CCNODE.H \
    CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_OPT=1 CCKPREAD.C
BUILD/CCKPWRITE-GEN.S: BUILD CCKPWRITE.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCKPCODE.H \
    CCNODE.H CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCKPWRITE.C
BUILD/CCLEX.S: BUILD CCLEX.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCLEX.C
BUILD/CCNODE.S: BUILD CCNODE.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCNODE.C
BUILD/CCNODE-GEN.S: BUILD CCNODE.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCNODE.C
BUILD/CCOPT.S: BUILD CCOPT.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCOPT.C
BUILD/CCOUT-CPP.S: BUILD CCOUT.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCNODE.H \
    CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_CPP=1 CCOUT.C
BUILD/CCOUT-OPT.S: BUILD CCOUT.C C-ENV.H CC.H CCCHAR.H CCCODE.H CCERR.H CCGEN.H CCNODE.H \
    CCPARM.H CCREG.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_OPT=1 CCOUT.C
BUILD/CCOUTUTIL.S: BUILD CCOUTUTIL.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H \
    CCREG.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCOUTUTIL.C
BUILD/CCPP.S: BUILD CCPP.C C-ENV.H CC.H CCCHAR.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSRC.H \
    CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCPP.C
BUILD/CCPPIN.S: BUILD CCPPIN.C C-ENV.H CC.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCPHASE.H CCSYM.H \
    CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCPPIN.C
BUILD/CCPPOUT.S: BUILD CCPPOUT.C C-ENV.H CC.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCPHASE.H \
    CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCPPOUT.C
BUILD/CCREG.S: BUILD CCREG.C C-ENV.H CC.H CCCODE.H CCERR.H CCGEN.H CCNODE.H CCPARM.H CCREG.H \
    CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCREG.C
BUILD/CCSRC.S: BUILD CCSRC.C CCSRC.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCSRC.C
BUILD/CCSTMT.S: BUILD CCSTMT.C C-ENV.H CC.H CCERR.H CCLEX.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCSTMT.C
BUILD/CCSYM.S: BUILD CCSYM.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCSYM.C
BUILD/CCSYM-CPP.S: BUILD CCSYM.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_CPP=1 CCSYM.C
BUILD/CCSYM-GEN.S: BUILD CCSYM.C C-ENV.H CC.H CCCHAR.H CCERR.H CCNODE.H CCPARM.H CCSYM.H \
    CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCSYM.C
BUILD/CCTYPE.S: BUILD CCTYPE.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCTYPE.C
BUILD/CCTYPE-GEN.S: BUILD CCTYPE.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) -DKCC_PHASE_GEN=1 CCTYPE.C
BUILD/CCVLA.S: BUILD CCVLA.C C-ENV.H CC.H CCERR.H CCNODE.H CCPARM.H CCSYM.H CCTOKS.H CCVLA.H
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) CCVLA.C
BUILD/DAIMOS-CHAIN.S: BUILD RUNTIME/DAIMOS-CHAIN.C

	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) RUNTIME/DAIMOS-CHAIN.C
BUILD/DAIMOS-PATH.S: BUILD RUNTIME/DAIMOS-PATH.C

	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) RUNTIME/DAIMOS-PATH.C
BUILD/DAIMOS-DRIVER.S: BUILD RUNTIME/DAIMOS-DRIVER.C
	@$(NATIVE_KCC) -S -O $@ $(KCC_NATIVE_FLAGS) RUNTIME/DAIMOS-DRIVER.C
BUILD/KCC.DXR: BOOT/CRT0.DOBJ BOOT/BOOT.DOBJ BOOT/SYS.DOBJ BOOT/HELP.DOBJ BUILD/DAIMOS-DRIVER.DOBJ \
    BOOT/LIBC.DARC
	@$(NATIVE_DLINK) --DAIMOS-UUO-RELAX -B 020 -O $@ $^
INSTALL: NATIVE
	@$(NATIVE_INSTALL) -D -M 0755 $(NATIVE_KCC_LIBEXEC)
	@$(NATIVE_INSTALL) -M 0555 BUILD/KCPP.DXR $(NATIVE_KCC_LIBEXEC)/KCPP
	@$(NATIVE_INSTALL) -M 0555 BUILD/KPARSE.DXR $(NATIVE_KCC_LIBEXEC)/KPARSE
	@$(NATIVE_INSTALL) -M 0555 BUILD/KGEN.DXR $(NATIVE_KCC_LIBEXEC)/KGEN
	@$(NATIVE_INSTALL) -M 0555 BUILD/KOPT.DXR $(NATIVE_KCC_LIBEXEC)/KOPT
	@$(NATIVE_INSTALL) -M 0555 BUILD/KCC.DXR $(NATIVE_KCC)
CLEAN:
	@$(NATIVE_RM) -R -F BUILD
