# Shared KCC build inventory. Use PLATFORM=DAIMOS for the native build.
# The staged SIXBIT file is uppercased and uses DAIMOS.MK.
PLATFORM ?= unix

# A prefixed, source-suffixed list permits portable GNU/BSD substitutions.

NATIVE_BUILD_SRCS = $(NATIVE_BUILD_DIR)/cc.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccasmb.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/cccreg.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/cccse.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/cccode.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccdata.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccdbug.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccdecl.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccerr.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/cceval.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccgen.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccgen1.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccgen2.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccgswi.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccjskp.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/cclex.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccnode.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccout.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccoututil.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccpp.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccsrc.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccreg.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccstmt.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccsym.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/cctype.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccopt.c
NATIVE_BUILD_SRCS += $(NATIVE_BUILD_DIR)/ccvla.c
NATIVE_ASMS = $(NATIVE_BUILD_SRCS:.c=.s)
NATIVE_OBJS = $(NATIVE_BUILD_SRCS:.c=.dobj)
NATIVE_DAIMOS_LIBC_ROOT = $(KCC_ROOT)/$(NATIVE_BUILD_DIR)/daimos-libc
NATIVE_DAIMOS_LIBC_DIR = $(NATIVE_DAIMOS_LIBC_ROOT)/libc
NATIVE_DAIMOS_LIBC = $(NATIVE_DAIMOS_LIBC_DIR)/libc.a
NATIVE_DAIMOS_SYSCALL_OBJ = $(NATIVE_DAIMOS_LIBC_DIR)/syscall.dobj
NATIVE_LINK_RUNTIME = $(NATIVE_RUNTIME_DIR)/crt0.dobj
NATIVE_LINK_RUNTIME += $(NATIVE_RUNTIME_DIR)/daimos-bootstrap.dobj
NATIVE_LINK_RUNTIME += $(NATIVE_DAIMOS_SYSCALL_OBJ)
NATIVE_LINK_RUNTIME += $(NATIVE_RUNTIME_DIR)/syscall-helpers.dobj
NATIVE_KCPP_DXR = $(NATIVE_BUILD_DIR)/KCPP.dxr
NATIVE_KPARSE_DXR = $(NATIVE_BUILD_DIR)/KPARSE.dxr
NATIVE_KGEN_DXR = $(NATIVE_BUILD_DIR)/KGEN.dxr
NATIVE_KOPT_DXR = $(NATIVE_BUILD_DIR)/KOPT.dxr
NATIVE_DRIVER_DXR = $(NATIVE_BUILD_DIR)/KCC.dxr
NATIVE_PHASE_DXRS = $(NATIVE_KCPP_DXR)
NATIVE_PHASE_DXRS += $(NATIVE_KPARSE_DXR)
NATIVE_PHASE_DXRS += $(NATIVE_KGEN_DXR)
NATIVE_PHASE_DXRS += $(NATIVE_KOPT_DXR)
NATIVE_PHASE_ASMS = $(NATIVE_CPP_ASMS)
NATIVE_PHASE_ASMS += $(NATIVE_CORE_ASMS)
NATIVE_PHASE_ASMS += $(NATIVE_GEN_ASMS)
NATIVE_PHASE_ASMS += $(NATIVE_PARSE_ASMS)
NATIVE_PHASE_ASMS += $(NATIVE_OPT_ASMS)

# Native phase link membership: each list names logical .c variants, some of
# which are not physical source files (for example ccdata-gen.c). Compile
# rules map variants to their real sources and select the phase defines.
# Portable GNU/BSD suffix substitution derives .dobj paths; runtime objects
# retain their separate directory. Preserve link order.
NATIVE_KCPP_MODULES = $(NATIVE_BUILD_DIR)/cc-cpp.c
NATIVE_KCPP_MODULES += $(NATIVE_BUILD_DIR)/ccasmb.c
NATIVE_KCPP_MODULES += $(NATIVE_BUILD_DIR)/ccdata-cpp.c
NATIVE_KCPP_MODULES += $(NATIVE_BUILD_DIR)/ccerr-cpp.c
NATIVE_KCPP_MODULES += $(NATIVE_BUILD_DIR)/ccout-cpp.c
NATIVE_KCPP_MODULES += $(NATIVE_BUILD_DIR)/ccpp.c
NATIVE_KCPP_MODULES += $(NATIVE_BUILD_DIR)/ccppout.c
NATIVE_KCPP_MODULES += $(NATIVE_BUILD_DIR)/ccsym-cpp.c
NATIVE_KCPP_MODULES += $(NATIVE_BUILD_DIR)/ccsrc.c
NATIVE_KCPP_OBJS = $(NATIVE_KCPP_MODULES:.c=.dobj)

# Historical standalone CORE object target (not linked by make native).
NATIVE_KCC1_MODULES = $(NATIVE_BUILD_DIR)/cc-core.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccasmb.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/cccreg.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/cccse.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/cccode.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccdata-core.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccdbug.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccdecl.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccerr-core.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/cceval.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccgen-core.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccgen1.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccgen2.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccgswi.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccjskp.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/cclex.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccnode.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccout-core.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccreg.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccstmt.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccsym.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/cctype.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccopt.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccoututil.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccppin.c
NATIVE_KCC1_MODULES += $(NATIVE_BUILD_DIR)/ccvla.c
NATIVE_KCC1_OBJS = $(NATIVE_KCC1_MODULES:.c=.dobj)

NATIVE_KPARSE_MODULES = $(NATIVE_BUILD_DIR)/cc-parse.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/ccasmb.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/ccdata-parse.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/ccbind-parse.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/ccdbug.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/ccdecl.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/ccerr-parse.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/cceval.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/cclex.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/ccnode.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/ccppin.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/ccstmt.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/ccsym.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/cctype.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/ccoututil.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/cckirwrite.c
NATIVE_KPARSE_MODULES += $(NATIVE_BUILD_DIR)/ccvla.c
NATIVE_KPARSE_OBJS = $(NATIVE_KPARSE_MODULES:.c=.dobj) $(NATIVE_RUNTIME_DIR)/daimos-chain.dobj $(NATIVE_RUNTIME_DIR)/daimos-path.dobj

NATIVE_KGEN_MODULES = $(NATIVE_BUILD_DIR)/cckgen-gen.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/cccreg.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/cccse.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/cccode-gen.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccdata-gen.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccdbug.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccerr-gen.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccevalgen.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccgen-gen.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccgen1-gen.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccgen2.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccgswi.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccjskp.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccnode-gen.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccreg.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccsym-gen.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/cctype-gen.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccopt.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccoututil.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/cckpout-gen.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/cckpwrite-gen.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/cckirread.c
NATIVE_KGEN_MODULES += $(NATIVE_BUILD_DIR)/ccvla.c
NATIVE_KGEN_OBJS = $(NATIVE_KGEN_MODULES:.c=.dobj) $(NATIVE_RUNTIME_DIR)/daimos-chain.dobj $(NATIVE_RUNTIME_DIR)/daimos-path.dobj

NATIVE_KOPT_MODULES = $(NATIVE_BUILD_DIR)/cckopt-opt.c
NATIVE_KOPT_MODULES += $(NATIVE_BUILD_DIR)/cckpread-opt.c
NATIVE_KOPT_MODULES += $(NATIVE_BUILD_DIR)/ccout-opt.c
NATIVE_KOPT_MODULES += $(NATIVE_BUILD_DIR)/ccoututil.c
NATIVE_KOPT_MODULES += $(NATIVE_BUILD_DIR)/ccdata-opt.c
NATIVE_KOPT_MODULES += $(NATIVE_BUILD_DIR)/ccerr-opt.c
NATIVE_KOPT_MODULES += $(NATIVE_BUILD_DIR)/ccasmb.c
NATIVE_KOPT_OBJS = $(NATIVE_KOPT_MODULES:.c=.dobj) $(NATIVE_RUNTIME_DIR)/daimos-path.dobj


include $(PLATFORM).mk
